### ISSUE TITLE
Adding option to specify ffmpeg path

### ISSUE THREAD

**Issue by akatora28** [techwarriorz/simple-hls#3]
What about adding an option to support specifying the ffmpeg path, mainly for easy support for [@ffmpeg-installer](https://github.com/kribblo/node-ffmpeg-installer)

If you add an additional parameter to the options object, `ffmpegPath`, you can reference that in index.ts line 19, or fallback to the default system version.

```ts
const ls = this.options.ffmpegPath ? spawn(this.options.ffmpegPath, commands) : spawn('ffmpeg', commands);
```

Happy to submit a PR

**Comment by techwarriorz** [comment]
If you submit the PR, I'll approve and include it in the next release :) Thank you!

**Comment by akatora28** [comment]
Sounds good, [submitted!](https://github.com/techwarriorz/simple-hls/pull/4)  

One thing to note, I did rename the const `ls` to `ffmpeg` since that's the variable that stores the ffmpeg child_process. In fluent-ffmpeg they name that variable `ffmpegProc` to provide even more clarity that it's the child_process that is referenced there.  

Whether you want to call that var `ffmpeg` or `ffmpegProc` I think is just a matter of personal preference for you as the repo owner, just wanted to flag that I did make that change though since I think it's important to rename it something ffmpeg related for readability

**Comment by techwarriorz** [comment]
PR has been approved to branch `release-0.0.2` and will be added to the end-of-month release.

Thank you for your contribution!
