### ISSUE TITLE
Transcode to only 2 bitrate 480 and 1080? 

### ISSUE THREAD

**Issue by Zaka-Ullah** [techwarriorz/simple-hls#5]
How  it could be done

**Comment by techwarriorz** [comment]
This can be achieved by using `custom renditions`

`const customRenditions = [
    {
        width: 840,
        height: 480,
        profile: 'main',
        hlsTime: '4',
        bv: '1400k',
        maxrate: '1498',
        bufsize: '2100k',
        ba: '128k',
        ts_title: '480p',
        master_title: '480p'
    },
    {
        width: 1920,
        height: 1080,
        profile: 'main',
        hlsTime: '4',
        bv: '5000k',
        maxrate: '5350k',
        bufsize: '7500k',
        ba: '192k',
        ts_title: '1080p',
        master_title: '1080p'
    }
];
    ]

    const t = new Transcoder(inputPath, outputPath, {renditions: customRenditions});
    try {
        const hlsPath = await t.transcode();
        console.log('Successfully Transcoded Video');
    } catch(e){
        console.log('Something went wrong');
    }`
